name: CI

on: push

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: ssciwr/setup-mesa-dist-win@v1
      - uses: ssciwr/setup-mesa-dist-win@v1
        with:
          version: '22.1.6'
          build-type: 'release-mingw'
          deployment-choice: '5'
